import re

singular_map = {
    "departments": "department", "specialties": "specialty", "academic_periods": "academic_period",
    "lesson_types": "lesson_type", "room_types": "room_type", "time_slots": "time_slot",
    "teachers": "teacher", "subjects": "subject", "groups": "group",
    "group_subgroups": "subgroup", "rooms": "room", "teacher_preferences": "teacher_preference",
    "teacher_load": "teacher_load", "teacher_subjects": "teacher_subject",
    "subject_lesson_types": "subject_lesson_type", "subject_room_type": "subject_room_type",
    "teacher_unavailability": "teacher_unavailability", "group_unavailability": "group_unavailability",
    "room_unavailability": "room_unavailability", "group_subject_load": "group_subject_load",
    "schedule_generation_runs": "generation_run", "schedule_conflicts_log": "schedule_conflict",
    "schedule": "schedule"
}

with open('college_schedule_production_schema.sql', 'r', encoding='utf-8') as f:
    sql = f.read()

# 1. Сначала исправим все REFERENCES и определения PK
# Это самая безопасная часть
for table, singular in singular_map.items():
    pk_original = f"{singular}_id"
    # Определение PK: "  pk_original BIGINT ..." -> "  id BIGINT ..."
    sql = re.sub(rf'^(\s+){pk_original}(\s+BIGINT\s+GENERATED)', r'\1id\2', sql, flags=re.MULTILINE)
    # Внешние ссылки: "REFERENCES table(pk_original)" -> "REFERENCES table(id)"
    sql = re.sub(rf'REFERENCES\s+{table}\s*\(\s*{pk_original}\s*\)', f'REFERENCES {table}(id)', sql)
    # INSERT: "INSERT INTO table (pk_original," -> "INSERT INTO table (id,"
    sql = re.sub(rf'INSERT INTO {table}\s*\(\s*{pk_original}\s*,', f'INSERT INTO {table} (id,', sql)
    # Имена столбцов в UNIQUE: например в group_subgroups (group_id, subgroup_id) -> (group_id, id)
    # Мы ищем UNIQUE (..., pk_original, ...)
    # Но чтобы не переименовать FK, мы проверяем только сам pk_original
    # Используем замену внутри скобок UNIQUE
    def fix_unique(m):
        return m.group(1) + re.sub(rf'\b{pk_original}\b', 'id', m.group(2)) + ')'
    sql = re.sub(rf'(UNIQUE\s*\()(.*?)(\))', fix_unique, sql, flags=re.DOTALL)

# 2. Ручные исправления триггеров (хирургически)
# Мы заменяем обращения к PK текущей таблицы в триггерах
sql = sql.replace("gs.subgroup_id", "gs.id")
sql = sql.replace("NEW.subgroup_id", "NEW.id")
sql = sql.replace("COALESCE(NEW.id, -1)", "COALESCE(NEW.id, -1)") # Уже id

sql = sql.replace("s.schedule_id", "s.id")
sql = sql.replace("NEW.schedule_id", "NEW.id")

sql = sql.replace("gsl.group_subject_load_id", "gsl.id")
sql = sql.replace("NEW.group_subject_load_id", "NEW.id")

# 3. Индексы
for table, singular in singular_map.items():
    pk_original = f"{singular}_id"
    # CREATE INDEX idx_table_pk_original ON table (pk_original)
    sql = re.sub(rf'CREATE INDEX\s+idx_{table}_{pk_original}', f'CREATE INDEX idx_{table}_id', sql)
    sql = re.sub(rf'ON\s+{table}\s*\(\s*{pk_original}\s*\)', f'ON {table}(id)', sql)

# 4. Auth tables
if "CREATE TABLE IF NOT EXISTS users" not in sql:
    sql = sql.replace("COMMIT;", """
-- ---------------------------------------------------------
-- App authentication and system models
-- ---------------------------------------------------------

DO $$ BEGIN
    CREATE TYPE userrole AS ENUM ('ADMIN', 'DISPATCHER', 'TEACHER', 'STUDENT', 'MANAGEMENT');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role userrole NOT NULL DEFAULT 'STUDENT',
    teacher_id BIGINT REFERENCES teachers(id) ON DELETE SET NULL,
    group_id BIGINT REFERENCES groups(id) ON DELETE SET NULL,
    full_name VARCHAR(200),
    is_not_student BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action VARCHAR(50) NOT NULL,
    entity VARCHAR(50) NOT NULL,
    entity_id BIGINT,
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_settings (
    key VARCHAR(50) PRIMARY KEY,
    value VARCHAR(255),
    description VARCHAR(200)
);

COMMIT;
""")

with open('college_schedule_production_schema_fixed.sql', 'w', encoding='utf-8') as f:
    f.write(sql)
