import re

tables = [
    "departments", "specialties", "academic_periods", "lesson_types", "room_types",
    "time_slots", "teachers", "subjects", "groups", "group_subgroups", "rooms",
    "teacher_preferences", "teacher_load", "teacher_subjects", "subject_lesson_types",
    "subject_room_type", "teacher_unavailability", "group_unavailability",
    "room_unavailability", "group_subject_load", "schedule_generation_runs",
    "schedule_conflicts_log", "schedule"
]

singular_map = {
    "departments": "department",
    "specialties": "specialty",
    "academic_periods": "academic_period",
    "lesson_types": "lesson_type",
    "room_types": "room_type",
    "time_slots": "time_slot",
    "teachers": "teacher",
    "subjects": "subject",
    "groups": "group",
    "group_subgroups": "subgroup",
    "rooms": "room",
    "teacher_preferences": "teacher_preference",
    "teacher_load": "teacher_load",
    "teacher_subjects": "teacher_subject",
    "subject_lesson_types": "subject_lesson_type",
    "subject_room_type": "subject_room_type",
    "teacher_unavailability": "teacher_unavailability",
    "group_unavailability": "group_unavailability",
    "room_unavailability": "room_unavailability",
    "group_subject_load": "group_subject_load",
    "schedule_generation_runs": "generation_run",
    "schedule_conflicts_log": "schedule_conflict",
    "schedule": "schedule"
}

with open('college_schedule_production_schema.sql', 'r', encoding='utf-8') as f:
    sql = f.read()

# 1. Rename Primary Keys in Definitions and REFERENCES
for table, singular in singular_map.items():
    pk_original = f"{singular}_id"
    
    # PK definition
    sql = re.sub(rf'(\s+){pk_original}(\s+BIGINT\s+GENERATED)', r'\1id\2', sql)
    
    # Foreign Key references
    sql = re.sub(rf'REFERENCES\s+{table}\s*\(\s*{pk_original}\s*\)', f'REFERENCES {table}(id)', sql)
    
    # INSERT statements
    sql = re.sub(rf'INSERT INTO {table}\s*\(\s*{pk_original}\s*,', f'INSERT INTO {table} (id,', sql)

# 2. Rename specifically inside trigger functions
# We only rename [table_singular]_id to id when it refers to the PK of the table used in that context
# Based on the grep analysis:

# group_subgroups trigger
sql = sql.replace("gs.subgroup_id", "gs.id")
sql = sql.replace("COALESCE(NEW.subgroup_id, -1)", "COALESCE(NEW.id, -1)")

# schedule triggers
sql = sql.replace("s.schedule_id", "s.id")
sql = sql.replace("COALESCE(NEW.schedule_id, -1)", "COALESCE(NEW.id, -1)")

# group_subject_load related
sql = sql.replace("gsl.group_subject_load_id", "gsl.id")
sql = sql.replace("NEW.group_subject_load_id", "NEW.id")

# Indices
for table, singular in singular_map.items():
    pk_original = f"{singular}_id"
    # CREATE INDEX ... ON table (pk_original)
    sql = re.sub(rf'(ON\s+{table}\s*\()\s*{pk_original}\s*(\))', r'\1id\2', sql)
    # INDEXES usually happen on FKs mostly, but if on PK:
    sql = re.sub(rf'CREATE INDEX\s+idx_{table}_{pk_original}', f'CREATE INDEX idx_{table}_id', sql)

# 3. Add the missing tables (users, audit_logs, app_settings) at the end if not already there
if "CREATE TABLE IF NOT EXISTS users" not in sql:
    sql = sql.replace("COMMIT;", """
-- ---------------------------------------------------------
-- App authentication and system models
-- ---------------------------------------------------------

DO $$ BEGIN
    CREATE TYPE userrole AS ENUM ('ADMIN', 'DISPATCHER', 'TEACHER', 'STUDENT', 'MANAGEMENT');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role userrole NOT NULL DEFAULT 'STUDENT',
    teacher_id BIGINT REFERENCES teachers(id) ON DELETE SET NULL,
    group_id BIGINT REFERENCES groups(id) ON DELETE SET NULL,
    full_name VARCHAR(200),
    is_not_student BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action VARCHAR(50) NOT NULL,
    entity VARCHAR(50) NOT NULL,
    entity_id BIGINT,
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_settings (
    key VARCHAR(50) PRIMARY KEY,
    value VARCHAR(255),
    description VARCHAR(200)
);

COMMIT;
""")

with open('college_schedule_production_schema_fixed.sql', 'w', encoding='utf-8') as f:
    f.write(sql)
