import re

singular_map = {
    "departments": "department", "specialties": "specialty", "academic_periods": "academic_period",
    "lesson_types": "lesson_type", "room_types": "room_type", "time_slots": "time_slot",
    "teachers": "teacher", "subjects": "subject", "groups": "group",
    "group_subgroups": "subgroup", "rooms": "room", "teacher_preferences": "teacher_preference",
    "teacher_load": "teacher_load", "teacher_subjects": "teacher_subject",
    "subject_lesson_types": "subject_lesson_type", "subject_room_type": "subject_room_type",
    "teacher_unavailability": "teacher_unavailability", "group_unavailability": "group_unavailability",
    "room_unavailability": "room_unavailability", "group_subject_load": "group_subject_load",
    "schedule_generation_runs": "generation_run", "schedule_conflicts_log": "schedule_conflict",
    "schedule": "schedule"
}

with open('college_schedule_production_schema.sql', 'r', encoding='utf-8') as f:
    sql = f.read()

# 1. Сначала исправляем REFERENCES во всем файле
for table, singular in singular_map.items():
    pk_original = f"{singular}_id"
    sql = re.sub(rf'REFERENCES\s+{table}\s*\(\s*{pk_original}\s*\)', f'REFERENCES {table}(id)', sql)

# 2. Исправляем определения таблиц (PK и Constraints)
def fix_table_block(match):
    table_name = match.group(1)
    content = match.group(2)
    singular = singular_map.get(table_name)
    if not singular:
        return match.group(0)
    
    pk_name = f"{singular}_id"
    # Заменяем pk_name на id, но только если это не часть REFERENCES (мы их уже исправили)
    # И не часть FOREIGN KEY (другого стобца)
    # Самое простое - заменить целиком слово pk_name, но исключая случаи "REFERENCES ... (pk_name)"
    # Однако в блоке CREATE TABLE текущей таблицы pk_name встречается в:
    # - Определении столбца: "pk_name BIGINT ..."
    # - UNIQUE констрейнтах: "UNIQUE (..., pk_name, ...)"
    # - РЕКОРДНО редко в REFERENCES на саму себя (но здесь такого нет)
    
    # Заменяем только если это не начало строки REFERENCES
    lines = content.split('\n')
    new_lines = []
    for line in lines:
        if 'REFERENCES' in line and (f'({pk_name})' in line or f' {pk_name} ' in line):
             # Если это внешняя ссылка на другую таблицу, но имя столбца совпадает с текущим PK
             # Мы его переименовываем только если это определение этого столбца или наш PK
             # В этом скрипте имена FK обычно совпадают с PK целевой таблицы.
             # Поэтому в таблице 'group_subgroups', 'group_id' - это FK, а 'subgroup_id' - PK.
             # Мы переименовываем 'subgroup_id' -> 'id'.
             pass
        
        # Заменяем pk_name на id
        # Используем границы слов, чтобы не задеть части других имен
        line = re.sub(rf'\b{pk_name}\b', 'id', line)
        new_lines.append(line)
    
    return f'CREATE TABLE {table_name} (' + '\n'.join(new_lines) + '\n);'

# Регулярка для захвата блока CREATE TABLE
# Используем затвор, чтобы не уйти за пределы скобки
sql = re.sub(r'CREATE TABLE ([a-zA-Z0-9_]+) \((.*?)\)\s*;', fix_table_block, sql, flags=re.DOTALL)

# 3. Исправляем INSERT
for table, singular in singular_map.items():
    pk_original = f"{singular}_id"
    # INSERT INTO table (pk_original, ...) -> INSERT INTO table (id, ...)
    sql = re.sub(rf'INSERT INTO {table}\s*\(\s*{pk_original}\b', f'INSERT INTO {table} (id', sql)

# 4. Исправляем триггеры и функции
for table, singular in singular_map.items():
    pk_original = f"{singular}_id"
    # NEW.pk_original -> NEW.id (только если это уместно)
    # В этом скрипте триггеры обычно на ту же таблицу, чьи поля они трогают
    # Но есть сложные. Проще оставить NEW.id если это PK.
    sql = re.sub(rf'\b(NEW|OLD|{table}|{singular})\.{pk_original}\b', r'\1.id', sql)

# 5. Исправляем оставшиеся UNIQUE констрейнты и прочее в функциях
# (Часть уже могла быть исправлена в NEW.id)
sql = sql.replace("gs.subgroup_id", "gs.id")
sql = sql.replace("s.schedule_id", "s.id")

# 6. Добавляем системные таблицы
if "CREATE TABLE IF NOT EXISTS users" not in sql:
    sql = sql.replace("COMMIT;", """
-- ---------------------------------------------------------
-- App authentication and system models
-- ---------------------------------------------------------

DO $$ BEGIN
    CREATE TYPE userrole AS ENUM ('ADMIN', 'DISPATCHER', 'TEACHER', 'STUDENT', 'MANAGEMENT');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role userrole NOT NULL DEFAULT 'STUDENT',
    teacher_id BIGINT REFERENCES teachers(id) ON DELETE SET NULL,
    group_id BIGINT REFERENCES groups(id) ON DELETE SET NULL,
    full_name VARCHAR(200),
    is_not_student BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action VARCHAR(50) NOT NULL,
    entity VARCHAR(50) NOT NULL,
    entity_id BIGINT,
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_settings (
    key VARCHAR(50) PRIMARY KEY,
    value VARCHAR(255),
    description VARCHAR(200)
);

COMMIT;
""")

with open('college_schedule_production_schema_fixed.sql', 'w', encoding='utf-8') as f:
    f.write(sql)
